export const URL_API = "://localhost:3000" 
export const URL_API_OFERTAS = URL_API+"/ofertas"
export const URL_API_COMO_USAR = URL_API+"/como-usar"
export const URL_API_ONDE_FICA = URL_API+"/onde-fica"
export const URL_PEDIDOS = URL_API+"/pedidos"
